### ISSUE TITLE
Fix grammar mistakes in greetings workflow

### ISSUE THREAD

**Issue by ajharry69** [ajharry69/xently-shopping-mobile#17]
Workflow file: https://github.com/ajharry69/xently-shopping-mobile/blob/main/.github/workflows/greetings.yml

**Comment by Ankit8848** [comment]
@ajharry69 I have to change only grammar?

**Comment by ajharry69** [comment]
Sure, @Ankit8848. An example of the current text with grammar errors can be found [here](https://github.com/ajharry69/xently-shopping-mobile/issues/12#issuecomment-1646328901).
